---
stages:
- name: Build Java Projects
  inputs:
  - type: git
    branch: ${BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: DOCKER_DIR
    value: ${DOCKER_DIR}
    type: text
  - name: BUILD_TARGET
    value: ${BUILD_TARGET}
    type: text
  jobs:
  - name: Build Java
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
        #!/bin/bash
        echo "Run gradle build..."
        export JAVA_HOME=~/java8
        export PATH=$JAVA_HOME/bin:$PATH
        /bin/bash build-microservice.sh
        cp ${BUILD_TARGET} ${DOCKER_DIR}/app.jar
        ls -al $PWD
        echo "Gradle build complete."

- name: Build Docker Image
  inputs:
  - type: job
    stage: Build Java Projects
    job: Build Java
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: LABEL_PREFIX
    value: ${LABEL_PREFIX}
    type: text
  - name: DOCKER_DIR
    value: ${DOCKER_DIR}
    type: text
  - name: REGION
    value: ${REGION}
    type: text
  - name: ORG
    value: ${ORG}
    type: text
  - name: SPACE
    value: ${SPACE}
    type: text
  - name: PATTERN
    value: ${PATTERN}
    type: text
  - name: NAME
    value: ${NAME}
    type: text
  jobs:
  - name: Build container
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      region_id: ${REGION}
      organization: ${ORG}
      space: ${SPACE}
    IMAGE_NAME: ${NAME}
    USE_CACHED_LAYERS: 'true'
    COMMAND: |-
      #!/bin/bash
        # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.
        log_and_echo "$LABEL" "Starting build script"
        cd ${WORKSPACE}/${DOCKER_DIR}
        # The IBM Container BM Containers plug-in (cf ic), Git client (git), and IDS Inventory CLI (ids-inv) have been installed.
        # Based on the organization and space selected in the Job credentials are in place for both IBM Container Service and IBM Bluemix
        #####################
        # Run unit tests    #
        #####################
        log_and_echo "$LABEL" "No unit tests cases have been checked in"
        ######################################
        # Build Container via Dockerfile     #
        ######################################
        # REGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}
        FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${LABEL_PREFIX}${APPLICATION_VERSION}
        # If you wish to receive slack notifications, set SLACK_WEBHOOK_PATH as a property on the stage.
        if [ -f Dockerfile ]; then
            log_and_echo "$LABEL" "Building ${FULL_REPOSITORY_NAME}"
            ${EXT_DIR}/utilities/sendMessage.sh -l info -m "New container build requested for ${FULL_REPOSITORY_NAME}"
            # build image
            BUILD_COMMAND=""
            if [ "${USE_CACHED_LAYERS}" == "true" ]; then
                BUILD_COMMAND="build --pull --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}/${DOCKER_DIR}"
                ice_retry ${BUILD_COMMAND}
                RESULT=$?
            else
                BUILD_COMMAND="build --no-cache --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}/${DOCKER_DIR}"
                ice_retry ${BUILD_COMMAND}
                RESULT=$?
            fi
            if [ $RESULT -ne 0 ]; then
                log_and_echo "$ERROR" "Error building image"
                ice_retry info
                ice_retry images
                ${EXT_DIR}/print_help.sh
                ${EXT_DIR}/utilities/sendMessage.sh -l bad -m "Container build of ${FULL_REPOSITORY_NAME} failed. $(get_error_info)"
                exit 1
            else
                log_and_echo "$SUCCESSFUL" "Container build of ${FULL_REPOSITORY_NAME} was successful"
                ${EXT_DIR}/utilities/sendMessage.sh -l good -m "Container build of ${FULL_REPOSITORY_NAME} was successful"
            fi
        else
            log_and_echo "$ERROR" "Dockerfile not found in project"
            ${EXT_DIR}/utilities/sendMessage.sh -l bad -m "Failed to get Dockerfile. $(get_error_info)"
            exit 1
        fi

        ######################################################################################
        # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE    #
        ######################################################################################
        echo "IMAGE_NAME=${FULL_REPOSITORY_NAME}" >> $ARCHIVE_DIR/build.properties
- name: Deploy Microservice
  inputs:
  - type: job
    stage: Build Docker Image
    job: Build container
  triggers:
  - type: stage
  properties:
  - name: MIN_INSTANCES
    value: ${MIN_INSTANCES}
    type: text
  - name: MAX_INSTANCES
    value: ${MAX_INSTANCES}
    type: text
  - name: DESIRED_INSTANCES
    value: ${DESIRED_INSTANCES}
    type: text
  - name: CONCURRENT_VERSIONS
    value: ${CONCURRENT_VERSIONS}
    type: text
  - name: AUTO_RECOVERY
    value: 'false'
    type: text
  - name: CONTAINER_SIZE
    value: ${CONTAINER_SIZE}
    type: text
  - name: IGNORE_MAPPING_ROUTE
    value: ${IGNORE_MAPPING_ROUTE}
    type: text
  - name: BRIDGE_APP
    value: ${BRIDGE_APP}
    type: text
  - name: BIND_TO
    value: ${BRIDGE_APP}
    type: text
  - name: REGION
    value: ${REGION}
    type: text
  - name: ORG
    value: ${ORG}
    type: text
  - name: SPACE
    value: ${SPACE}
    type: text
  - name: PATTERN
    value: ${PATTERN}
    type: text
  - name: NAME
    value: ${NAME}
    type: text
  - name: PORT
    value: ${PORT}
    type: text
  - name: ROUTE_DOMAIN
    value: ${ROUTE_DOMAIN}
    type: text
  - name: ROUTE_HOSTNAME
    value: ${ROUTE_HOSTNAME}
    type: text
  - name: TEST_RESULT_FOR_AD
    value: ${TEST_RESULT_FOR_AD}
    type: text
  - name: GROUP_SIZE
    value: ${GROUP_SIZE}
    type: text
  - name: DEBUG
    value: ${DEBUG}
    type: text
  - name: GIT_HOME
    value: ${GIT_HOME}
    type: text
  - name: RAMPDOWN_DURATION
    value: ${RAMPDOWN_DURATION}
    type: text
  - name: RAMPUP_DURATION
    value: ${RAMPUP_DURATION}
    type: text
  jobs:
  - name: Deploy Container Group
    type: deployer
    extension_id: ibm.devops.services.pipeline.docker.deploy.ice
    target:
      region_id: ${REGION}
      organization: ${ORG}
      space: ${SPACE}
    DEPLOY_TYPE: simple
    PORT: ${PORT}
    CONTAINER_NAME: ${NAME}
    COMMAND: |-
       #!/bin/bash

        # -------------- #
        # Set debug mode #
        # -------------- #

        if [[ -n ${DEBUG} ]]; then set -x ; fi

        # The following are some example deployment scripts.  Use these as is or fork them and include your updates here:
        echo -e "${label_color}Starting deployment script${no_color}"
        # To view/fork this script goto: https://github.com/Osthanes/deployscripts
        # git_retry will retry git calls to prevent pipeline failure on temporary github problems
        # the code can be found in git_util.sh at https://github.com/Osthanes/container_deployer
        git_retry clone https://github.com/Osthanes/deployscripts.git deployscripts

        # -------------------------------------------------- INFO ------------------------------------------------------------ #

        # ------ Single container ------- #

        # Optional environment properties (can be set directly in this script, or defined as environment properties):
        #      NAME              Value         Description
        #   =============      =========     ==============
        #   BIND_TO             String       Specify a Bluemix application name that whose bound services you wish to make available to the container.  By default this is not set.
        #   CONTAINER_SIZE      String       Specify container size: pico (64), nano (128), micro (256), tiny (512), small (1024), medium (2048), large (4096), x-large (8192), 2x-large (16384). Default is micro (256).
        #   CONCURRENT_VERSIONS Number       Number of versions of this container to leave active. Default is 1

        # -------------------------------------------------------------------------------------------------------------------- #

        /bin/bash deployscripts/deploycontainer.sh

        if [[ ${NAME} == *"hystrix"* ]]; then
          IP_ADDRESS=`cf ic ip list | grep -e '.*[0-9]\.[0-9].*' | head -n1 | sed 's/ *//g'`
          CONTAINER_ID=`cf ic ps | grep ${CONTAINER_NAME}_${BUILD_NUMBER} | awk '{print $1}'`
          cf ic ip bind ${IP_ADDRESS} ${CONTAINER_ID}
          if [ $? -ne 0 ]; then
            echo -e "${red}[ERROR]: An error ocurred binding the IP address to the Hystrix container${no_label}"
            exit 1
          fi
        fi

        RESULT=$?
        # source the deploy property file
        if [ -f "${DEPLOY_PROPERTY_FILE}" ]; then
          source "$DEPLOY_PROPERTY_FILE"
        fi

        #########################
        # Environment DETAILS   #
        #########################
        # The environment has been setup.
        # The Cloud Foundry CLI (cf), IBM Container Service CLI (ice), Git client (git), IDS Inventory CLI (ids-inv) and Python 2.7.3 (python) have been installed.
        # Based on the organization and space selected in the Job credentials are in place for both IBM Container Service and IBM Bluemix
        # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.
        if [ $RESULT -ne 0 ]; then
            echo -e "${red}Executed failed or had warnings ${no_color}"
            ${EXT_DIR}/print_help.sh
            exit $RESULT
        fi
        echo -e "${green}Execution complete${no_label}"

        export NAME="${CONTAINER_NAME}_${BUILD_NUMBER}"
        echo "Value of NAME: ${NAME}"
